[package]
name = "search-stack-exchange"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aleph-alpha-client = "0.3.0"
atoi = "1.0.0"
clap = { version = "3.2.20", features = ["derive"] }
quick-xml = "0.24.0"
thiserror = "1.0.32"

[dev-dependencies]
tokio = { version = "1.15.0", features = ["rt", "macros"] }
lazy_static = "1.4.0"
ordered-float = "3.0.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

